FROM node:20-alpine AS deps
WORKDIR /src
COPY app/package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine AS build
WORKDIR /src
COPY --from=deps /src/node_modules ./node_modules
COPY app/ ./

FROM node:20-alpine AS runtime
WORKDIR /app
COPY --from=build /src ./

EXPOSE 3000
CMD ["node", "index.js"]
