name: Variation Branch Behavior

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: variation-branch-behavior-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-or-manual-build:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@develp
        with:
          app_token: ${{secrets.IR_API_KEY}}
          api_url: "https://app.stage.invisirisk.com"
          mode: docker-intercept
      # ============= InvisiRisk Setup End =============
      - uses: actions/checkout@v4
      - name: Fast validation build
        run: docker build -f docker/Dockerfile.raw -t sample-docker-build:pr-fast --build-arg BUILDKIT_SYNTAX=public.ecr.aws/w3c0c0n7/invisirisk/baf-buildkit:dev-test --secret id=pse-ca,src=/etc/ssl/certs/pse.pem --build-arg PSE_PROXY=http://${PSE_PROXY_IP}:3128 .
      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@develp
        with:
          cleanup: "true"
          api_url: "https://app.stage.invisirisk.com"
      # ============= InvisiRisk Cleanup End =============

  main-extended-build:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@develp
        with:
          app_token: ${{secrets.IR_API_KEY}}
          api_url: "https://app.stage.invisirisk.com"
          mode: docker-intercept
      # ============= InvisiRisk Setup End =============
      - uses: actions/checkout@v4
      - name: Extended build
        run: docker build -f docker/Dockerfile.multistage -t sample-docker-build:main-extended --build-arg BUILDKIT_SYNTAX=public.ecr.aws/w3c0c0n7/invisirisk/baf-buildkit:dev-test --secret id=pse-ca,src=/etc/ssl/certs/pse.pem --build-arg PSE_PROXY=http://${PSE_PROXY_IP}:3128 .
      - name: Smoke
        uses: ./.github/actions/smoke-test
        with:
          image: sample-docker-build:main-extended
          name: main-extended
          host-port: "18114"
      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@develp
        with:
          cleanup: "true"
          api_url: "https://app.stage.invisirisk.com"
      # ============= InvisiRisk Cleanup End =============